# Generated by Django 5.1.2 on 2024-10-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_ability_characterclass_dndcharacter_race_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DndCharacter',
            new_name='Character',
        ),
    ]
