# Generated by Django 5.1.2 on 2024-10-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_rename_dndcharacter_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
