# Generated by Django 5.1.2 on 2024-10-21 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character_armor_class_character_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='parent_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.race'),
        ),
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(choices=[('TY', 'Tiny'), ('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('HG', 'Huge'), ('GT', 'Gargantuan')], default='MD', max_length=2),
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.IntegerField(default=30),
        ),
    ]
