# Generated by Django 5.1.2 on 2024-10-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_race_description_race_parent_race_race_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='parent_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='character.race'),
        ),
    ]
